### ISSUE TITLE
REQUIREMENT: Unique values for specified fields

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dcap#42]
#21 
This is a relationship between values. This may require a defined record or graph over which this is calculated

**Comment by kcoyle** [comment]
In the shapes work there was a requirement to have only one value per language tag. This would be valid:

rdf:label "woman"@en
rdf:label "donna"@it
rdf:label "frau"@de

But this would not be:

rdf: label "dog"@en
rdf:label "canine"@en

Should we include this in this requirement, or create a new requirement?

**Comment by philbarker** [comment]
I think one value per language tag would be appropriate here.
However, (unless I am missing it) I think there should be a use case requirement for [a] specific language[s] (e.g. I am aggregating data for an English speaking audience, I require english labels & litterals; or "I'm Switzerland, any of these five languages will do" etc.). The two together could give a requirement for one and only one label. I could add it as a requirement from use case #19 if you like.

**Comment by kcoyle** [comment]
Yes, that's another requirement that has come up in the past. Please add it to #19. I'll create two requirements: 1) be able to define only one value per language and 2) be able to limit to a list of languages. (Note: ShEx has the second one as ["value sets".](http://shexspec.github.io/primer/#value-sets))

**Comment by philbarker** [comment]
OK, have edited #19 to add language requirement

**Comment by kcoyle** [comment]
This is covered by #47
