### ISSUE TITLE
USE CASE: Managing dates

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dcap#44]
Creator: Karen Coyle

## Problem statement
I have places in my metadata where I include dates. Of course, the dates need to be in a standard format. However, the real problem is that I want to check the dates for some level of accuracy. For example, for published books I want to be sure that the dates are later than 1500 and not later than one year past the current date. This is to avoid errors like a date coded as "9156" or "1050" instead of "1956". 

The other date-related problem is that of making sure that birth dates and death dates of authors are reasonable. The main check here is to make sure that the birth date is at least one year after the death date. The vocabulary will use the properties from the [BIO](http://vocab.org/bio/) vocabulary, bio:birth and bio:death. The check must compare the dates between these two properties.

## Stakeholders
Input staff will need to get immediate feedback on errors so that they can correct them. Development staff will need a way to define the rules for dates. Programs ingesting existing data will also need to be able to validate dates.

## Links
''Optional link list to documents and projects this use case refers to''

## Requirements
* Define minimum and maximum _values_ for a property
* Define rules for comparison between the values of two or more properties

## Comments
''Optional section for editorial comments, suggestion and their interactive resolution''

**Comment by marianamalta** [comment]
@kcoyle Shouldn't the second requirement "compare..:" a requirement that has more to do with the software that "is used to introduce the values" and not a concern of an application profile definition?

**Comment by kcoyle** [comment]
@marianamalta Yes, I will re-word that. The AP has to define what the rules are between the two values; software will indeed do the comparing.

**Comment by kcoyle** [comment]
Covered in #45
