### ISSUE TITLE
REQUIREMENT: labels for profile entities and terms

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dcap#50]
#49

**Comment by tombaker** [comment]
@kcoyle How is this different from #22 ?

**Comment by kcoyle** [comment]
It isn't, really, and I noticed that when gathering requirements. We can mark it as a duplicate.

**Comment by tombaker** [comment]
Closing as an issue because it is a duplicate of #22.

**Comment by kcoyle** [comment]
Closing. I don't remember why I reopened it but it has been incorporated into our basic model.
