### ISSUE TITLE
REQUIREMENT: AP must be able to have definitions for terms

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dcap#51]
#49 

Definitions can be text or a link

**Comment by tombaker** [comment]
@kcoyle How is this different from #22 ?

**Comment by kcoyle** [comment]
There's only a minor difference, in that this one specifically addresses "definitions" not just descriptions. I'm not sure that they are different, but they come from different use cases. If we determine that they are the same, we can combine them.

**Comment by tombaker** [comment]
For the SWIB presentation, I plan not to list this one because it is so close to #22.

**Comment by kcoyle** [comment]
This is covered in the `note` column in DC TAP
