### ISSUE TITLE
REQUIREMENT: AP must be able to have instructions for input and use, as text, as links or both

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dcap#52]
#49

**Comment by tombaker** [comment]
@kcoyle How is this different from #30 ?

**Comment by kcoyle** [comment]
It seems quite different to me. This is about guidance, whereas #30 is about pick lists. Maybe you meant a different issue?

**Comment by kcoyle** [comment]
DC TAP has a column `note` available on each row that can contain text or links or both.
