### ISSUE TITLE
Quickstatements-like way to write ShEx expressions

### ISSUE THREAD

**Issue by johnsamuelwrites** [dcmi/dcap#57]
One possible extension to the approach by the [tabular representation of ShEx expression](https://github.com/dcmi/dcap/blob/master/painting/E130.ipynb) is to make use of [Quickstatements](https://www.wikidata.org/wiki/Help:QuickStatements)-like expressions. 

Following are the key columns in the above example

Entity_name | Entity_label | Property | Property_label | Cardinality | Value | Value_type | Annotation
-- | -- | -- | -- | -- | -- | -- | --

So, we need 4 characters: E, P, C, V
Labels, descriptions (or annotations) and type can be abbreviated to L, D and T respectively.

So, 

painting | Painting | wdt:P31 | Is a | 1..1 | wd:Q3305213 | URI | instance of "painting"
-- | -- | -- | -- | -- | -- | -- | --

can be represented as 

Een "painting" ELen "Painting" P31 PLen "instance of" Vwd:Q3305213 VC1..1 VT "URI"
Den "instance of painting"

**Comment by tombaker** [comment]
@johnsamuelwrites An interesting approach!  How might you get from this syntax to a ShEx schema (in ShExC or ShExJ)?  Could the tooling around Quickstatements help with that?

**Comment by kcoyle** [comment]
It seems to me that we have the "meta" issue here as well. Each column in the table is a property so we could in theory have a P value for each column. The Q value would be the profile, with its properties. Thinking about this, though, it doesn't seem to save much effort, does it? What it would do is give a display that wikidata editors could read 'natively'.

**Comment by kcoyle** [comment]
Great idea. Someone could definitely do this! If so, we'll put it in the cookbook so others see it.
