### ISSUE TITLE
Rename "value type" to "node type"

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dcap#68]
We have tentatively settled on 2 columns that define the type of the value:

value type: one of "Literal, non-literal, URI, BNODE"
value datatype: any datatype defined in the xsd list

and then there will be 2 columns that define the constraints on the value (which must be consistent with the type):

value constraint type: to be defined, but necessary to interpret the next column
value constraint: the expression of the actual constraint, such as a list of strings, a list of URI stems, a ShEx snippet, a formula, a regex.

I am afraid that "value type" will be confusing on the surface because many will confuse it with "value datatype". The significant meaning of the "value type" column is that it is the node type of the object of the predicate/property in the propertyID column. For this reason I think we should rename this "value type" to reflect the fact that it is an RDF node type, not a datatype. I'm suggesting "node type" but there may be other names that would get that across: "value node type" "RDF node type" etc.

W3C document that defines nodes: https://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/#section-rdf-graph

**Comment by tombaker** [comment]
Could we call it "RDF value type"? People who know RDF would know what this is, while others could simply disregard it. We could bury this somewhere in the documentation where only experts or developers would look.

So: 'value_type' => 'rdfvalue_type' (or maybe even 'rdf_valuetype' or 'rdf_value_type').

**Comment by tombaker** [comment]
For the same reason (to avoid confusion), 'value_datatype' should perhaps be called 'literal_value_datatype'.

**Comment by kcoyle** [comment]
@tombaker "anyURI" is an XSD type, so it isn't just literals. However, it now occurs to me that we may need a synonym for "anyURI" = "URI".

**Comment by philbarker** [comment]
I think I prefer "value RDF type" a) for consistency with all the others that start with value, and b) because its the RDF [node] type of the value.

**Comment by philbarker** [comment]
I wrote this earlier but then deleted it by accident. Sorry about the repetition.

@kcoyle wrote:

> @tombaker "anyURI" is an XSD type, so it isn't just literals. However, it now occurs to me that we may need a synonym for "anyURI" = "URI".

I don't think this is correct. RDF 1.1 Concepts and Abstract Syntax [section on datatypes](https://www.w3.org/TR/rdf11-concepts/#section-Datatypes) says:

> Datatypes are used with RDF literals to represent values such as strings, numbers and dates.

[RDF Translator](http://rdf-translator.appspot.com/) treats 
```
[] sdo:url "https://www.dublincore.org/"^^xsd:anyURI .
```
as a literal value, using the URL for a JSON-LD `@value`, whereas
```
[] sdo:url <https://www.dublincore.org/> .
```
is treated as a URIRef, using the URL as a JSON-LD `@id`.


I think it would take more than renaming to clarify this for many users.

**Comment by tombaker** [comment]
@philbarker Thank you for the clarification.  

@all If `xsd:anyURI` tags a literal after all,  would you support renaming `value_datatype` to `literal_value_datatype` (or perhaps to `datatype` for the column heading with "Literal Value Datatype" as its full name)?

**Comment by kcoyle** [comment]
No, I wouldn't support it because we still need to be able to have URI as a datatype in that column, regardless of this (surprising to me) RDF treatment of xsd:anyURI as a literal. But this isn't the question in this issue, which is the naming of the column that will take RDF node types as values.

**Comment by kcoyle** [comment]
Opening new issue for URI as datatype in #70

**Comment by tombaker** [comment]
We went for valueNodeType as per the ["simple template"](https://github.com/dcmi/dcap/blob/master/prototypes/simple/simpleTemplate.csv) - see [diff](https://github.com/dcmi/dcap/commit/ca3ceb899afab58db64f1cc7ca3a7651f7ee249c#diff-9f6649a8fabb2b55b65d134fc77b61aacb7b41cc25638bd6dfe8caec28ecb9ae)
